import type { BibleWheelBook } from './bible-wheel.types';

/**
 * Slim Bible book data for the wheel (no verse arrays).
 * Exact match to Angular BibleBooks projection.
 */
export const BIBLE_BOOKS: BibleWheelBook[] = [
  { position: 1,  longname: "The Book of Genesis",        shortname: "Gen", chapters: 50 },
  { position: 2,  longname: "The Book of Exodus",         shortname: "Exo", chapters: 40 },
  { position: 3,  longname: "The Book of Leviticus",      shortname: "Lev", chapters: 27 },
  { position: 4,  longname: "The Book of Numbers",        shortname: "Num", chapters: 36 },
  { position: 5,  longname: "The Book of Deuteronomy",    shortname: "Deut", chapters: 34 },
  { position: 6,  longname: "The Book of Joshua",         shortname: "Josh", chapters: 24 },
  { position: 7,  longname: "The Book of Judges",         shortname: "Judg", chapters: 21 },
  { position: 8,  longname: "The Book of Ruth",           shortname: "Ruth", chapters: 4 },
  { position: 9,  longname: "The First Book of Samuel",   shortname: "1 Sam", chapters: 31 },
  { position: 10, longname: "The Second Book of Samuel",  shortname: "2 Sam", chapters: 24 },
  { position: 11, longname: "The First Book of Kings",    shortname: "1 Kgs", chapters: 22 },
  { position: 12, longname: "The Second Book of Kings",   shortname: "2 Kgs", chapters: 25 },
  { position: 13, longname: "The First Book of Chronicles", shortname: "1 Chr", chapters: 29 },
  { position: 14, longname: "The Second Book of Chronicles", shortname: "2 Chr", chapters: 36 },
  { position: 15, longname: "The Book of Ezra",           shortname: "Ezra", chapters: 10 },
  { position: 16, longname: "The Book of Nehemiah",       shortname: "Neh", chapters: 13 },
  { position: 17, longname: "The Book of Esther",         shortname: "Esth", chapters: 10 },
  { position: 18, longname: "The Book of Job",            shortname: "Job", chapters: 42 },
  { position: 19, longname: "The Book of Psalms",         shortname: "Psa", chapters: 150 },
  { position: 20, longname: "The Book of Proverbs",       shortname: "Prov", chapters: 31 },
  { position: 21, longname: "The Book of Ecclesiastes",   shortname: "Eccl", chapters: 12 },
  { position: 22, longname: "The Song of Solomon",        shortname: "Song", chapters: 8 },
  { position: 23, longname: "The Book of Isaiah",         shortname: "Isa", chapters: 66 },
  { position: 24, longname: "The Book of Jeremiah",       shortname: "Jer", chapters: 52 },
  { position: 25, longname: "The Book of Lamentations",   shortname: "Lam", chapters: 5 },
  { position: 26, longname: "The Book of Ezekiel",        shortname: "Ezek", chapters: 48 },
  { position: 27, longname: "The Book of Daniel",         shortname: "Dan", chapters: 12 },
  { position: 28, longname: "The Book of Hosea",          shortname: "Hos", chapters: 14 },
  { position: 29, longname: "The Book of Joel",           shortname: "Joel", chapters: 3 },
  { position: 30, longname: "The Book of Amos",           shortname: "Amos", chapters: 9 },
  { position: 31, longname: "The Book of Obadiah",        shortname: "Obad", chapters: 1 },
  { position: 32, longname: "The Book of Jonah",          shortname: "Jonah", chapters: 4 },
  { position: 33, longname: "The Book of Micah",          shortname: "Mic", chapters: 7 },
  { position: 34, longname: "The Book of Nahum",          shortname: "Nah", chapters: 3 },
  { position: 35, longname: "The Book of Habakkuk",       shortname: "Hab", chapters: 3 },
  { position: 36, longname: "The Book of Zephaniah",      shortname: "Zeph", chapters: 3 },
  { position: 37, longname: "The Book of Haggai",         shortname: "Hag", chapters: 2 },
  { position: 38, longname: "The Book of Zechariah",      shortname: "Zech", chapters: 14 },
  { position: 39, longname: "The Book of Malachi",        shortname: "Mal", chapters: 4 },
  { position: 40, longname: "The Book of Matthew",        shortname: "Matt", chapters: 28 },
  { position: 41, longname: "The Book of Mark",           shortname: "Mark", chapters: 16 },
  { position: 42, longname: "The Book of Luke",           shortname: "Luke", chapters: 24 },
  { position: 43, longname: "The Book of John",           shortname: "John", chapters: 21 },
  { position: 44, longname: "The Book of Acts",           shortname: "Acts", chapters: 28 },
  { position: 45, longname: "The Book of Romans",         shortname: "Rom", chapters: 16 },
  { position: 46, longname: "The First Book of Corinthians", shortname: "1 Cor", chapters: 16 },
  { position: 47, longname: "The Second Book of Corinthians", shortname: "2 Cor", chapters: 13 },
  { position: 48, longname: "The Book of Galatians",      shortname: "Gal", chapters: 6 },
  { position: 49, longname: "The Book of Ephesians",      shortname: "Eph", chapters: 6 },
  { position: 50, longname: "The Book of Philippians",    shortname: "Phil", chapters: 4 },
  { position: 51, longname: "The Book of Colossians",     shortname: "Col", chapters: 4 },
  { position: 52, longname: "The First Book of Thessalonians", shortname: "1 Thess", chapters: 5 },
  { position: 53, longname: "The Second Book of Thessalonians", shortname: "2 Thess", chapters: 3 },
  { position: 54, longname: "The First Book of Timothy",  shortname: "1 Tim", chapters: 6 },
  { position: 55, longname: "The Second Book of Timothy", shortname: "2 Tim", chapters: 4 },
  { position: 56, longname: "The Book of Titus",          shortname: "Titus", chapters: 3 },
  { position: 57, longname: "The Book of Philemon",       shortname: "Phlm", chapters: 1 },
  { position: 58, longname: "The Book of Hebrews",        shortname: "Heb", chapters: 13 },
  { position: 59, longname: "The Book of James",          shortname: "Jas", chapters: 5 },
  { position: 60, longname: "The First Book of Peter",    shortname: "1 Pet", chapters: 5 },
  { position: 61, longname: "The Second Book of Peter",   shortname: "2 Pet", chapters: 3 },
  { position: 62, longname: "The First Book of John",     shortname: "1 John", chapters: 5 },
  { position: 63, longname: "The Second Book of John",    shortname: "2 John", chapters: 1 },
  { position: 64, longname: "The Third Book of John",     shortname: "3 John", chapters: 1 },
  { position: 65, longname: "The Book of Jude",           shortname: "Jude", chapters: 1 },
  { position: 66, longname: "The Book of Revelation",     shortname: "Rev", chapters: 22 },
];
